Feat/create sign in route
Grupo-GCB/expense-tracker-backend pull request #11
Opened 2023-08-02 22:37 UTC by Diogo-gallina

# Criação do caso de uso de login 

Desenvolvi o caso de uso de login, onde ele recebe um jwt verifica se é valido e retorna o payload. 
Caso o email do usuário não esteja registrado no banco, o usuário é registrado. 
Também realizei todos testes unitários.

Solicitante(s) da tarefa
- Kayke Fujinaka

Card(s) da tarefa

- [Implementar login no Backend](https://dev.azure.com/GCBInvestimentos/Academy%202.0/_sprints/taskboard/Academy%202.0%20Team/Academy%202.0/Sprint%201?workitem=22477)

# Checklist

Você realizou o code review do seu próprio PR?

- [x] Sim
- [ ] Não

---

Necessário seguir alguma ordem de deploy (ex: aceitar outro PR antes)?

- [ ] Sim
- [x] Não

### Testes que precisa ser realizado para aprovação do PR

- [x] Produtos
- [ ] Ux/Ui
- [ ] QA

Responsáveis pelos testes QA:

- Kayke Fujinaka

2023-08-02 23:01 UTC, shimarrudz requested changes

2023-08-02 23:01 UTC, shimarrudz commented on src/shared/infra/http/controllers/user/user.controller.ts
> +import { Request, Response } from 'express';
Colocar nos imports de libs no começo do código

2023-08-02 23:03 UTC, Kayke-Fujinaka requested changes

2023-08-02 23:03 UTC, Kayke-Fujinaka commented on src/auth/providers/jwt-auth-provider/jwt-auth-provider.ts
> +      jwksUri: 'https://gcb-academy.us.auth0.com/.well-known/jwks.json',
Armazena isso em uma variável ou coloca no .env

2023-08-02 23:03 UTC, Kayke-Fujinaka commented on src/auth/providers/jwt-auth-provider/jwt-auth-provider.ts
> +    const publicKey = signingKey.getPublicKey();
Coloca isso em um outro método apenas para pegar a chave pública `getPublicKey`

2023-08-02 23:03 UTC, Kayke-Fujinaka commented on src/auth/providers/jwt-auth-provider/jwt-auth-provider.ts
> +      throw new Error('Cabeçalho de token inválido.');
Cria um método para separar o código `decodeJwtHeader`

2023-08-03 01:31 UTC, Diogo-gallina commented on src/user/use-cases/sign-in/sign-in.ts
>      const user = await this.usersRepository.findByEmail(userPayload.email);
A lógica do meu siginUseCase está diferente desse comentário
`  async execute(token: string): Promise<{ status: number; message: string }> {
    let userPayload: SaveUserDTO;

    try {
      userPayload = await this.jwtAuthProvider.decodeToken(token);
    } catch (err: any) {
      throw new UnauthorizedException({
        message: 'Token inválido.',
        reason: err.message,
      });
    }`

2023-08-03 01:33 UTC, RafaRamosCosta requested changes

2023-08-03 01:46 UTC, Diogo-gallina commented on src/auth/auth.module.ts
> +    JwtAuthProvider,
Eu deixei apenas a de cima.
Se eu tiro a de cima o meu servidor cai.

2023-08-03 09:25 UTC, Kayke-Fujinaka requested changes

2023-08-03 09:25 UTC, Kayke-Fujinaka commented on src/auth/providers/jwt-auth-provider/jwt-auth-provider.ts
> +    return publicKey;
Retorna isso direto.

2023-08-03 09:25 UTC, Kayke-Fujinaka commented on src/auth/providers/jwt-auth-provider/jwt-auth-provider.ts
> +    if (!decodedHeader || !decodedHeader.header || !decodedHeader.header.kid) {
Cria uma variável armazenando essa condicional.
`const isDecodedHeaderValid = !decodedHeader ...`

2023-08-03 09:25 UTC, Kayke-Fujinaka commented on src/auth/providers/jwt-auth-provider/jwt-auth-provider.ts
> +        algorithms: ['RS256'],
Acha válido armazenar o `JWT_ALGORITHMS` no .env?

2023-08-03 10:35 UTC, Kayke-Fujinaka approved these changes

2023-08-03 13:22 UTC, joelgon requested changes

2023-08-03 13:22 UTC, joelgon commented on src/shared/infra/http/controllers/user/user.controller.ts
> +  @ApiUnauthorizedResponse({
faltou importar

2023-08-03 13:22 UTC, joelgon commented on src/shared/infra/http/controllers/user/user.controller.ts
> +    private listUserUseCase: ListUserByIdUseCase,
removeu o import

2023-08-03 13:22 UTC, joelgon commented on src/shared/infra/http/controllers/user/user.controller.ts
> -import { Controller, Get, HttpStatus, Param } from '@nestjs/common';
Param esta sendo usado na linha 78

2023-08-03 13:22 UTC, joelgon commented on src/shared/infra/http/controllers/user/user.controller.ts
> -import { User } from '@/user/infra/entities';
User esta sendo usado na linha 78

2023-08-03 13:22 UTC, joelgon commented on src/shared/infra/http/controllers/user/user.controller.ts
> +  @ApiBody({
muito verboso e pouco ultil @ApiBody

2023-08-03 13:22 UTC, joelgon commented on src/shared/infra/http/controllers/user/user.controller.ts
> +  async create(@Req() { body }: Request, @Res() res: Response) {
pq @Req() { body }: Request ao inves de @Body() body: UserTokenDTO? que inclusive se seu dto estiver usando ApiProperty já irá documentar no swagger

2023-08-03 14:38 UTC, Diogo-gallina commented on src/shared/infra/http/controllers/user/user.controller.ts
> +  async create(@Req() { body }: Request, @Res() res: Response) {
Tentei refatorar dessa maneira, mas quebra a minha lógica.

2023-08-03 17:06 UTC, Kayke-Fujinaka approved these changes

2023-08-03 18:22 UTC, guilhermetupi commented on src/auth/providers/jwt-auth-provider/jwt-auth-provider.ts
> +    if (isDecodedHeaderValid) {
Precisa existir o `decodedHeader.header.kid`? Se sim, pode colocar apenas `decodedHeader?.header?.kid`. Se nao, pode passar direto `if (!decodedHeader || !decodedHeader.header || !decodedHeader.header.kid)`, nao tem necessidade de criar uma variavel se nao vai utilizar ela alem da verificacao

2023-08-03 18:23 UTC, guilhermetupi commented on src/auth/providers/jwt-auth-provider/jwt-auth-provider.ts
> +        algorithms: ['RS256'],
Se esse eh o padrao tem necessiade de explicita-lo?

2023-08-03 18:25 UTC, guilhermetupi commented on src/user/dto/user-token-dto.ts
> +      'eyJhbGciOiJSUzI1NiIsInR5cCI6IasdasdweZCI6IkxjdU1WSmRRbjNjanRsV0NfNGh1dyJ9.eyJnaXZlbl9uYW1lIubkuSWEFdXN0byIsImZhbWlseV9uYW1lIjoic2FudGFuYSIsIm5pY2tuYW1lIjoiZ3V0eS52ZXJ0b2xpcyIsIm5hbWUiOiJhdWd1c
Nao precisa da quebra de linha

2023-08-03 18:27 UTC, guilhermetupi approved these changes

2023-08-03 18:50 UTC, Diogo-gallina commented on src/auth/providers/jwt-auth-provider/jwt-auth-provider.ts
> +    if (isDecodedHeaderValid) {
Ele precisa existir sim, pois ele é o key id, mas vou passar direto no if

2023-08-03 18:53 UTC, Diogo-gallina commented on src/user/dto/user-token-dto.ts
> +      'eyJhbGciOiJSUzI1NiIsInR5cCI6IasdasdweZCI6IkxjdU1WSmRRbjNjanRsV0NfNGh1dyJ9.eyJnaXZlbl9uYW1lIubkuSWEFdXN0byIsImZhbWlseV9uYW1lIjoic2FudGFuYSIsIm5pY2tuYW1lIjoiZ3V0eS52ZXJ0b2xpcyIsIm5hbWUiOiJhdWd1c
Se eu não quebrar a linha o Eslint e o Prettier lançam um erro.

2023-08-03 19:05 UTC, guilhermetupi commented on src/auth/providers/jwt-auth-provider/jwt-auth-provider.ts
> +    if (isDecodedHeaderValid) {
Isso, so passar `if(!decodedHeader?.header?.kid)` nao precisar do resto nem da variavel

2023-08-03 19:08 UTC, Diogo-gallina commented on src/auth/providers/jwt-auth-provider/jwt-auth-provider.ts
> +    const signingKey = await jwksClient.getSigningKey(kid);
Não consigo retornar assim diretamente por que o jwksClient.getSigningKey(kid) é uma promisse separada, mas eu deixei desse jeito:

`return (await jwksClient.getSigningKey(kid)).getPublicKey();`

2023-08-03 19:11 UTC, Diogo-gallina commented on src/auth/providers/jwt-auth-provider/jwt-auth-provider.ts
> +        algorithms: ['RS256'],
Eu tinha colocado para o jwt verify async, mas realmente não tem necessidade

2023-08-03 19:50 UTC, guilhermetupi requested changes

2023-08-03 19:50 UTC, guilhermetupi commented on src/shared/infra/http/controllers/user/user.controller.ts
> +  async signIn(@Req() { body }: Request, @Res() res: Response) {
Aqui vc tambem pode tipar a request  `async signIn(@Req() { body }: Request<{}, {}, UserTokenDTO>, @Res() res: Response)`

2023-08-03 19:50 UTC, guilhermetupi commented on src/user/use-cases/sign-in/sign-in.ts
> +      await this.usersRepository.create(userPayload);
Por que essas chamadas do repositorio nao estao no try catch? Como o resto da logica necessita do que esta dentro do try catch nao faz sentido ficar fora, alem de prevenir um possivel erro no repository, assim vc nao precisa declarar o `let userPayload: SaveUserDTO;` antes do try, pode deixar `const userPayload = await this.jwtAuthProvider.decodeToken(token);`

2023-08-03 20:12 UTC, guilhermetupi requested changes

2023-08-03 20:12 UTC, guilhermetupi commented on src/shared/infra/http/controllers/user/user.controller.ts
>      const { token } = body as UserTokenDTO;
como vc tipou a request nao precisa tipar o body aqui

2023-08-03 20:19 UTC, ArthurEnrique15 commented on src/shared/infra/database/typeorm/migrations/1690478202013-create-table-user.ts
pq tu alterou migrations que já foram criadas? elas n já tão em prod?

2023-08-03 20:19 UTC, ArthurEnrique15 commented on src/shared/infra/http/controllers/user/user.controller.ts
> +    private signInUseCase: SignInUseCase,
private readonly nos dois use cases aqui

2023-08-03 20:19 UTC, ArthurEnrique15 commented on src/user/use-cases/sign-in/sign-in.spec.ts
>  import { User } from '@/user/infra/entities';
tem uns imports não usados aqui

2023-08-03 20:19 UTC, ArthurEnrique15 commented on src/auth/providers/jwt-auth-provider/jwt-auth-provider.ts
> +  async decodeToken(jwtToken: string): Promise<SaveUserDTO> {
um padrão do clean code que eu acho q seria bom vc seguir, organiza os métodos na classe na ordem em que eles são usados. O decodeToken vem primeiro (no topo da classe), em seguida o decodeJwtHeader, e abaixo o getPublicKey

2023-08-03 20:19 UTC, ArthurEnrique15 commented on src/auth/providers/jwt-auth-provider/jwt-auth-provider.ts
> +    return (await jwksClient.getSigningKey(kid)).getPublicKey();
quebra essas chamadas aq, armazena o retorno em variáveis com bons nomes

primeiro ce chama o await jwksClient.getSigningKey(kid) e salva em uma variável
dps ce retorna a variável.getPublicKey()

uma coisa q eu recomendo vc nunca fazer é usar return await

2023-08-03 21:31 UTC, Diogo-gallina commented on src/shared/infra/database/typeorm/migrations/1690478202013-create-table-user.ts
Durante a execução do projeto, foram encontrados erros nas migrations por que as FK estavam erradas, ai eu configurei pra executar o código.

2023-08-03 21:53 UTC, Tuliolivieri commented on src/auth/interfaces/auth-provider.ts
> +export abstract class IAuthProvider {
Há algum motivo ou limitação do Nest/Node para usar uma classe abstrata ao invés de uma interface aqui, uma vez que o método abstrato não possui nenhuma implementação?

2023-08-03 22:11 UTC, RafaRamosCosta requested changes

2023-08-03 22:11 UTC, RafaRamosCosta commented on src/user/use-cases/sign-in/sign-in.spec.ts
> +  it('should return 200 if user already exists', async () => {
Isso é detalhe, mas vocês podem ser mais descritivos quando escreverem os its.
Ex: should be able to return a success response if user already exists.
Por que da forma como ta escrito aqui parece que o método deve retornar o número 200.

2023-08-03 22:11 UTC, RafaRamosCosta commented on src/user/use-cases/sign-in/sign-in.ts
> +    private jwtAuthProvider: JwtAuthProvider,
Tipar essa injeção com IAuthProvider e mudar o nome da variável para algo mais genérico como authProvider.

2023-08-03 22:11 UTC, RafaRamosCosta commented on src/user/use-cases/sign-in/sign-in.ts
> +  async execute(token: string): Promise<{ status: number; message: string }> {
Criar uma interface para utilizar em todos os métodos que retornam:
{ status: number; message: string }

2023-08-03 22:33 UTC, Kayke-Fujinaka approved these changes

2023-08-03 22:41 UTC, RafaRamosCosta approved these changes

2023-08-03 22:52 UTC, merged