Fix/user controller test
Grupo-GCB/expense-tracker-backend pull request #27
Opened 2023-08-09 23:43 UTC by Diogo-gallina

# Resolvendo erro em todos testes da controller de usuário

Solicitante(s) da tarefa

- Kayke Fujinaka

Card(s) da tarefa

- Não tem cards para esta tarefa

# Checklist

Você realizou o code review do seu próprio PR?

- [X] Sim
- [ ] Não

Necessário seguir alguma ordem de deploy (ex: aceitar outro PR antes)?

- [ ] Sim
- [X] Não

### Testes que precisa ser realizado para aprovação do PR

- [X] Produtos
- [ ] Ux/Ui
- [ ] QA

Responsáveis pelos testes QA:

- Kayke Fujinaka

2023-08-10 12:08 UTC, Kayke-Fujinaka requested changes

2023-08-10 12:19 UTC, Kayke-Fujinaka approved these changes

2023-08-10 13:15 UTC, RafaRamosCosta requested changes

2023-08-10 13:15 UTC, RafaRamosCosta commented on src/shared/infra/http/controllers/user/user.controller.e2e.spec.ts
>  import * as request from 'supertest';
subir esse import para manter o padão.

2023-08-10 13:15 UTC, RafaRamosCosta commented on src/shared/infra/http/controllers/user/user.controller.e2e.spec.ts
> +    const module: TestingModule = await Test.createTestingModule({
Não precisa dessa tipagem aqui, o createTestingModule.compile() já retorna isso.

2023-08-10 17:53 UTC, RafaRamosCosta approved these changes

2023-08-12 18:01 UTC, Kayke-Fujinaka approved these changes

2023-08-12 18:08 UTC, merged