Feat/sign-in-use-case
Grupo-GCB/expense-tracker-backend pull request #9
Opened 2023-07-29 21:34 UTC by Diogo-gallina

# Criação do caso de uso de listagem de usuário

Desenvolvi o caso de uso e realizei todos testes unitários.

Solicitante(s) da tarefa
- Kayke Fujinaka

Card(s) da tarefa

- [Implementar login no Backend](https://dev.azure.com/GCBInvestimentos/Academy%202.0/_sprints/taskboard/Academy%202.0%20Team/Academy%202.0/Sprint%201?workitem=22293)

# Checklist

Você realizou o code review do seu próprio PR?

- [x] Sim
- [ ] Não

---

Necessário seguir alguma ordem de deploy (ex: aceitar outro PR antes)?

- [ ] Sim
- [x] Não

### Testes que precisa ser realizado para aprovação do PR

- [x] Produtos
- [ ] Ux/Ui
- [ ] QA

Responsáveis pelos testes QA:

- Kayke Fujinaka

2023-07-30 14:58 UTC, LeonardoRCosta commented on src/user/interfaces/sign-in.ts
> +  email_virified: boolean;
Não seria email_verified?

2023-07-30 16:45 UTC, Kayke-Fujinaka requested changes

2023-07-30 16:45 UTC, Kayke-Fujinaka commented on src/user/dtos/save-user-dto.ts
> +  email: string;
Faltou colocar a documentação com o swagger.

Seguir o padrão que o Victor fez.

2023-07-30 16:45 UTC, Kayke-Fujinaka commented on src/user/user.module.ts
> +    JwtModule.register({ secret: 'hard!to-guess_secret' }),
Deixar o secret no .env!!

Colocar também no .env.example

2023-07-30 16:45 UTC, Kayke-Fujinaka commented on src/user/infra/repositories/users-repository.ts
> +    return user;
Pode retornar o this.usersRepository... direto.

```
return this.usersRepository.findOne({
      where: { email },
    });
```

2023-07-30 16:45 UTC, Kayke-Fujinaka commented on src/user/use-cases/sign-in/sign-in.ts
> +import { IDecodedTokenPayload } from '@/user/interfaces';
Arrumar o import!

Você pode pegar os dois de uma vez.

`import { IUsersRepository, IDecodedTokenPayload } from '@/user/interfaces';`

2023-07-30 16:45 UTC, Kayke-Fujinaka commented on src/user/use-cases/sign-in/sign-in.ts
> +  }
Se o usuário não existir quando ele buscar pelo e-mail, ele retornará o usuário quando criar.

Se o usuário existir quando ele buscar pelo e-mail, ele não retornará nada.

Não acha válido retornar o usuário caso exista?

2023-07-30 16:45 UTC, Kayke-Fujinaka commented on src/user/use-cases/sign-in/sign-in.spec.ts
> +      email: 'diogo.gallina@example.com',
Vamos deixar no padrão do John Doe para o do Victor ficar com ele e o seu com outros nomes, sendo assim, buscar ao máximo seguir uma combinação e padrão mútuo entre vocês.

2023-07-30 16:45 UTC, Kayke-Fujinaka commented on src/user/use-cases/sign-in/sign-in.spec.ts
> +    const token = 'valid-jwt-token';
Compartilha essa variável entre os outros testes para evitar escrever a mesma linha.

Você já cria para o token válido e inválido.

2023-07-30 16:45 UTC, Kayke-Fujinaka commented on src/user/use-cases/sign-in/sign-in.spec.ts
> +      email: 'diogo.gallina@example.com',
Muda de todos.

2023-07-31 11:56 UTC, Kayke-Fujinaka commented on src/user/dtos/save-user-dto.ts
> +    example: 'oauth2|6546846841681616844168',
Esse não é o id real do Augusto, né? 

Se for muda alguns números kkkkkkkkk

2023-07-31 12:01 UTC, Kayke-Fujinaka commented on src/user/infra/repositories/users-repository.ts
> +  async create(data: SaveUserDTO): Promise<User> {
Dá um enter entre essas linhas.

2023-07-31 12:17 UTC, Kayke-Fujinaka approved these changes

2023-07-31 12:59 UTC, LeonardoRCosta requested changes

2023-07-31 12:59 UTC, LeonardoRCosta commented on src/user/use-cases/sign-in/sign-in.spec.ts
> +  };
Como você está utilizando essa função em todos os casos de teste, você pode utilizar o beforeEach.

2023-07-31 13:05 UTC, Diogo-gallina commented on src/user/use-cases/sign-in/sign-in.spec.ts
> +  };
Certo! já vou alterar isso.

2023-07-31 14:21 UTC, shimarrudz requested changes

2023-07-31 14:21 UTC, shimarrudz commented on src/user/dtos/save-user-dto.ts
> +  @IsEmail({}, { message: 'Deve ser e-mail válido.' })
"Deve ser um e-mail válido"

2023-07-31 14:21 UTC, shimarrudz commented on src/user/use-cases/sign-in/sign-in.spec.ts
> +import { SignInUseCase } from './sign-in';
Adicionar path maping

2023-07-31 14:21 UTC, shimarrudz commented on src/user/use-cases/sign-in/sign-in.ts
> +      throw new UnauthorizedException();
Colocar resposta do erro em pt-br para padronização do código

2023-07-31 14:47 UTC, shimarrudz approved these changes

2023-07-31 15:04 UTC, merged